### ISSUE TITLE
Umsetzen der Version 3 

### ISSUE THREAD

**Issue by VYCanisMajori** [Seyuna/Bungalow#3]
Version: Kundennummern
• Woher weiß man nun, wer den Bungalow in der entsprechenen Woche gebucht hat?! (Richtig: man  weiß es bisher NICHT)
• Es wird nun also in der entsprechenden Woche neben der Anzahl der Gäste auch die Kundennummer  (4-stellige Ganzzahl, z.B.6567) gespeichert.

**Comment by Seyuna** [comment]
Muss noch visuell in GUI integriert werden
